import React from 'react';

const PrintReport = ({ title, children }) => {
  return (
    <div className="print-report print-hidden">
      <div className="print-header">
        <h1 className="print-title">{title}</h1>
        <div className="print-date">
          {new Date().toLocaleDateString('en-US', { 
            weekday: 'long', 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
          })}
        </div>
      </div>
      <div className="print-content">
        {children}
      </div>
      <div className="print-footer">
        <p>Generated by TrackNest Pro</p>
      </div>
    </div>
  );
};

export default PrintReport;