export const generateReceiptNumber = () => {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
  return `RCP-${year}${month}${day}-${random}`;
};

export const calculateSaleTotal = (items, discount = 0, tax = 0) => {
  const subtotal = items.reduce((sum, item) => sum + (item.total || 0), 0);
  const discountAmount = (subtotal * discount) / 100;
  const taxAmount = ((subtotal - discountAmount) * tax) / 100;
  return {
    subtotal,
    discountAmount,
    taxAmount,
    total: subtotal - discountAmount + taxAmount
  };
};

export const calculateStats = (sales, inventory) => {
  const totalSales = sales.reduce((sum, sale) => sum + sale.total, 0);
  const totalProfit = sales.reduce((sum, sale) => sum + sale.profit, 0);
  const lowStockItems = inventory.filter(item => item.status === 'low-stock').length;
  const outOfStockItems = inventory.filter(item => item.status === 'out-of-stock').length;

  return { totalSales, totalProfit, lowStockItems, outOfStockItems };
};

export const generateReceiptHTML = (sale) => {
  const totals = calculateSaleTotal(sale.items, sale.discount, sale.tax);
  return `
    <html>
      <head>
        <title>Sales Receipt</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; }
          .header { text-align: center; margin-bottom: 20px; }
          .receipt { border: 1px solid #ddd; padding: 20px; max-width: 400px; margin: 0 auto; }
          .item { display: flex; justify-content: space-between; margin: 5px 0; }
          .total { border-top: 1px solid #ddd; margin-top: 10px; padding-top: 10px; }
          .footer { text-align: center; margin-top: 20px; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="receipt">
          <div class="header">
            <h2>TrackNest Pro</h2>
            <p>Sales Receipt</p>
            <p>Date: ${new Date(sale.date).toLocaleDateString()}</p>
            <p>Receipt #: ${sale.receiptNumber || sale.id}</p>
          </div>
          
          <div>
            <p><strong>Customer:</strong> ${sale.customerName}</p>
            ${sale.customerPhone ? `<p><strong>Phone:</strong> ${sale.customerPhone}</p>` : ''}
            ${sale.customerEmail ? `<p><strong>Email:</strong> ${sale.customerEmail}</p>` : ''}
          </div>
          
          <hr>
          
          ${sale.items.map(item => `
            <div class="item">
              <span>${item.name} x${item.quantity}</span>
              <span>UGX ${item.total.toLocaleString()}</span>
            </div>
          `).join('')}
          
          <div class="total">
            <div class="item">
              <span>Subtotal:</span>
              <span>UGX ${totals.subtotal.toLocaleString()}</span>
            </div>
            ${sale.discount > 0 ? `
              <div class="item">
                <span>Discount (${sale.discount}%):</span>
                <span>-UGX ${totals.discountAmount.toLocaleString()}</span>
              </div>
            ` : ''}
            ${sale.tax > 0 ? `
              <div class="item">
                <span>Tax (${sale.tax}%):</span>
                <span>UGX ${totals.taxAmount.toLocaleString()}</span>
              </div>
            ` : ''}
            <div class="item">
              <strong>Total:</strong>
              <strong>UGX ${totals.total.toLocaleString()}</strong>
            </div>
          </div>
          
          <div>
            <p><strong>Payment Method:</strong> ${sale.paymentMethod}</p>
            ${sale.notes ? `<p><strong>Notes:</strong> ${sale.notes}</p>` : ''}
          </div>
          
          <div class="footer">
            <p>Thank you for your business!</p>
            <p>Generated by TrackNest Pro</p>
          </div>
        </div>
      </body>
    </html>
  `;
};
